### ISSUE TITLE
Animating removal from an `{{each}}`?

### ISSUE THREAD

**Issue by dfreeman** [gigafied/ember-animate#19]
First off, thanks for the great plugin! Super easy to get up and running with :)

I've got a collection of items, and I'd like to animate views as they enter and leave the collection. I've put together [a simple JS Bin](http://emberjs.jsbin.com/bitacixi/30/edit?html,js,output) illustrating the scenario -- it appears the elements are being removed from the DOM before the animation has time to execute.

It's more than possible I'm just mis-configuring this, so if that's the case I'd be grateful for a pointer in the right direction. Otherwise, I don't have a complete enough understanding of Ember's `ContainerView` to know whether this case should be (or even can be) accounted for, or if it's simply a limitation of the view stack as it stands today.

**Comment by gigafied** [comment]
Closing this as it's the same issue as issue #23
