### ISSUE TITLE
Animate-In Fails...Sometimes. (edited)

### ISSUE THREAD

**Issue by rubencodes** [gigafied/ember-animate#21]
Hello,
Thanks for the great tool! I've really enjoyed using it so far. However, I'm having an issue strictly on pages that have to load a model from an external resource. 
I initially found that with some specific pages, the animate-in wouldn't work *sometimes*. If an animation was triggered, the incoming view would just appear immediately, superimposing the new page on the previous page for a few milliseconds while the previous page animated out. Part of the weirdness is this only happens about half the time. It may happen, it may not happen.

I then linked this to only occurring on incoming pages with external models. I tried commenting out the models, and sure enough, the animation would work perfectly every time.
 
I'll note (on the off chance it's relevant) that I'm using async animations. Is this a known issue, or is there something I perhaps missed? Thanks.

EDIT: I think I may be mistaken on the trigger: I believe it may be related to transitioning using transitionToRoute() in an action vs a link-to handler, rather than being related to the model.

**Comment by gigafied** [comment]
Closing this unless you can provide further info.
