### ISSUE TITLE
AnimateIN not working

### ISSUE THREAD

**Issue by ambush276** [gigafied/ember-animate#29]
not sure exactly whats going on.. but animate out is working perfectly... animateIn not so much.

i currently have 2 views

script handlebars...   id="index"
and 

script handlebars ..... id="signup"

this is my views::
App.IndexView = Ember.View.extend({
    willAnimateIn : function () {
        this.$().css("opacity", 0);
    },

    animateIn : function (done) {
        this.$().fadeTo(500, 1, done);
    },

    animateOut : function (done) {
        this.$().fadeTo(500, 0, done);
    }
});

App.SignupView = Ember.View.extend({
    willAnimateIn : function () {
        this.$().css("opacity", 0);
    },

    animateIn : function (done) {
        this.$().fadeTo(500, 1, done);
    },

    animateOut : function (done) {
        this.$().fadeTo(500, 0, done);
    }
});

any suggestions?

**Comment by gigafied** [comment]
Please re-open if you still have an issue.
